# docker-compose.yml
services:
  db:
    image: postgres:latest
    container_name: test-postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    networks:
      - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: ./new/api  # Ruta correcta donde se encuentra el Dockerfile
      dockerfile: Dockerfile  # Nombre del Dockerfile en el directorio api
    container_name: myapp-container
    environment:
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      SECRET_KEY: ${SECRET_KEY}
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
